### ISSUE TITLE
Suggestions for main program

### ISSUE THREAD

**Issue by jefleponot** [tebelorg/TA.Gui#19]
Here is a list of issue about TA.Gui : 

- _**Why does the export file is a text file**_ ?

it could be better to use a  structured file for the data as XML or JSON (I prefer JSON because it is a native java-script object container)

1_yahoo

```txt
https://www.yahoo.com
// automation flow files start with an URL to tell TA.Gui where to go

// this flow searches github on Yahoo and captures screenshot of results
// for issues or questions, kindly feedback on GitHub or support@tebel.org
// see cheatsheet for steps, conditions, finding element identifiers, etc
// https://github.com/tebelorg/TA.Gui#cheat-sheet

// use type (or enter) step to enter some text into a webpage element
// use show (or print) step to print text from webpage element to output
// below steps enter text into the search box and print out the value
enter search-box as github
print search-box

// use tap (or click) step to click on a webpage element
// below step clicks the search button
click search-button

// wait a few seconds before capturing whole screenshot
// default wait is 5 seconds and you can also use decimal
// wait 7.5 seconds or 3s or 5sec or 10 secs will work 
wait 6.6

// use snap to save screenshot of webpage or elements
// use snap page to save screen shot of entire page
// use snap element to save screen shot of element
snap page
snap logo

// image snaps are automatically named snapXXXX.png
// unless you provide a filename for the image snap
snap page to results.png
snap logo to logo.png

// to go to another URL from your flow, simply provide the URL
https://duckduckgo.com

// and then continue the automation flow from there
enter search_form_input_homepage as The search engine that doesn\'t track you.

wait 4.4 seconds
```

vs 

```json
{
   steps : [
    {
        comment : "automation flow files start with an URL to tell TA.Gui where to go",
        type: "open",
        url: "https://www.yahoo.com"
    },
    {
        comment : "Fill inputText element",
        type: "enter",
        locator: "search-box",
        text: "github",
    },
    {
        comment : "print data",
        type: "print",
        locator: "search-box"
    },
    {
        comment : "click Event",
        type: "click",
        locator: "search-box"
    },
    {
        comment : "pause",
        type: "wait",
        waitTime: "6.6"
        measure: "second"
    }
  ]
}
```

- _**Why does yours  scripts are written in bash and php**_ ?

TA.Gui will never be used under Windows !!! but Windows is the OS used by no-developer.
It could be nice to write all script in javascript because casperJS and phantomJS and SlimerJS understand Javascript.

Tagui must start like that : 
```js
#!/bin/env /usr/bin/casperjs 
/*
 *  TA.GUI - Main code
 *  ------------------
 *
 * Documentation: 
 * Repository:    
 *
 * Copyright (c) Ken Soh (2017)
 * Licence: Celill http://www.cecill.info/
 *
 * [e-mail of the author(s)]
 * 
 * This software is a computer program whose purpose is to [describe
 * functionalities and technical features of your software].
 * 
 * This software is governed by the CeCILL license under French law and
 * abiding by the rules of distribution of free software.  You can  use, 
 * modify and/ or redistribute the software under the terms of the CeCILL
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info". 
 * 
 * As a counterpart to the access to the source code and  rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty  and the software's author,  the holder of the
 * economic rights,  and the successive licensors  have only  limited
 * liability. 
 * 
 * In this respect, the user's attention is drawn to the risks associated
 * with loading,  using,  modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean  that it is complicated to manipulate,  and  that  also
 * therefore means  that it is reserved for developers  and  experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or 
 * data to be ensured and,  more generally, to use and operate it in the 
 * same conditions as regards security. 
 * 
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

var tagui = { "version": "0.0.1" };

//--------------
// MAIN REQUIRE
// -------------
var _colorizer_ = require('colorizer').create('Colorizer');
var _fs_ = require('fs'), _system_=require('system'), _utils_ = require('utils');

_fs_.read(_fs_.pathJoin(binDir,'usage.txt');
```

Regards

**Comment by kensoh** [comment]
Hi @jefleponot many thanks for your suggestions!

- ***Why does the export file is a text file ?***

The overarching goal for the project now is to make automation accessible to more people and handle increasingly complex processes as cognitive abilities of computers continue to improve. To a large extent, I want non-developers and non-programmers to be able to have access to web automation tools. In that case the scripting language and file should be in plain text, so that more people will be able to edit, write or make changes easily.

Outputting in JSON is great, but it is only good for consumption by programs or other developers' API. It should be straightforward to write a convertor to convert a TA.Gui file into a JSON or XML form. I've noted on this and can work on this if there is a strong use case, after clearing out the big items like enhancing the Chrome extension and porting over to Windows. I am also not ruling out in the future, in addition to CasperJS/PhantomJS/SlimerJS, to output TA.Gui files directly into WebDriver and increase execution endpoints of the tool. That also supports the goal of making automation accessible.

- ***Why does yours scripts are written in bash and php ?***

Yes I mentioned in Set Up section that TA.Gui is still in beta and not yet ported to Windows, that's probably the reason for the error message you received for #18. The short reason for using bash and php is it allows me to prototype and develop at the fastest pace I can, and it breaks automation jobs (especially for batch automation) into separate instances by calling CasperJS/PhantomJS once for each iteration. I like this model for now as it becomes easy for people to implement batch testing and automation without possible issues due to long-running processes or possible memory garbage-handling issues. The long reason for the choice of using PHP/CasperJS/PhantomJS is here - https://github.com/tebelorg/TA.Gui/issues/16

I have been working full-time on this project without sponsorship or salary, so I will take the approach which lets me iterate and ship as fast as possible. Ultimately, as I make an automation tool that is accessible to more people, I want to use the tool myself to do automation of processes. Imho, current tooling for this purpose is just too cumbersome to rapidly develop or prototype automation of work processes. There are established RPA software in market, but they costs few thousand USD per user and are usually deployed through consulting firms which add even more to the cost. I would like to see the power of web automation be made available to people or businesses without the financial weight of large companies.

I've noted your suggestions and closing the issue. But please feel free to continue the discussion!

**Comment by jefleponot** [comment]
@kensoh 

Thank for your reply. I understand better that you want to do.

Do you known "ghost inspector" ?  https://ghostinspector.com/
It is very expensive but really user-friendly for a RPA software.

It could be nice if you (we) could make the equivalent in free software :-)
but you have before to find a business plan to finance your work (with partners firms).

And, you have to build the project onto a TTD (test plan). It lacks actually.

**Comment by jefleponot** [comment]
@kensoh 

Thank for your reply. I understand better that you want to do.

Do you known "ghost inspector" ?  https://ghostinspector.com/
It is very expensive but really user-friendly for a RPA software.

It could be nice if you (we) could make the equivalent in free software :-)
but you have before to find a business plan to finance your work (with partners firms).

And, you have to build the project onto a TTD (test plan). It lacks actually.


Just a screenshot of selenium builder user interface
![image](https://cloud.githubusercontent.com/assets/5547697/23659819/b61b5410-0347-11e7-94d0-49da4b12e835.png)

**Comment by jefleponot** [comment]
The more information you have => better it is :-)

**Comment by kensoh** [comment]
Hi @jefleponot, thanks for adding on :) yes I'm aware of Ghost Inspector (backend using CasperJS/PhantomJS). A start-up friend is also using it to test their website. It is very easy to use and also records videos of the test automation. What Justin had done in the few short years to Ghost Inspector is admirable.

A problem for cloud deployment is the software will need to pass on AWS / DigitalOcean etc cloud hosting costs to the users. My guess is that's the reason why it is really hard to deploy cloud-based automation services for free, because the service provider will end up having to absorb all the AWS / cloud-servers costs.

I've considered providing a cloud service base on TA.Gui/CasperJS/PhantomJS in order to make automation accessible to more people. However, I'm not moving in that direction until there is real demand for it. I feel the more cost efficient way is for users to simply run locally using the horse-power they already have on their laptops/servers. Just need to find a way to remove user-friction in set-up. In that way, the automation tool can be kept free. It might end up some users are willing to pay for running on cloud while most users simply run on their computers/servers.

Another problem with Ghost Inspector or Selenium based solutions, with reference to RPA, is user cannot have fine-tuned logic and programmatic control without actually writing code. They are great for test automation but for process automation code is still needed. As much as possible, I'm trying to make that happen without writing code through TA.Gui, while still supporting advanced coding if user is a developer.

Do you know if Selenium Builder is easily customizable to modify its generated output? I'm starting to work on the Chrome extension again (base on Resurrectio) to implement new function like capturing screenshots of webpage elements, hovering to an element and so on. Maybe if you are already working on Selenium-Builder solution it can be explored concurrently while I put on new functions through Resurrectio.

**Comment by kensoh** [comment]
Hi @jefleponot, thanks for adding on :) yes I'm aware of Ghost Inspector (backend using CasperJS/PhantomJS). A start-up friend is also using it to test their website. It is very easy to use and also records videos of the test automation. What Justin had done in the few short years to Ghost Inspector is admirable.

A problem for cloud deployment is the software will need to pass on AWS / DigitalOcean etc cloud hosting costs to the users. My guess is that's the reason why it is really hard to deploy cloud-based automation services for free, because the service provider will end up having to absorb all the AWS / cloud-servers costs.

I've considered providing a cloud service base on TA.Gui/CasperJS/PhantomJS in order to make automation accessible to more people. However, I'm not moving in that direction until there is real demand for it. I feel the more cost efficient way is for users to simply run locally using the horse-power they already have on their laptops/servers. Just need to find a way to remove user-friction in set-up. In that way, the automation tool can be kept free. It might end up some users are willing to pay for running on cloud while most users simply run on their computers/servers.

Another problem with Ghost Inspector or Selenium based solutions, with reference to RPA, is user cannot have fine-tuned logic and programmatic control without actually writing code. They are great for test automation but for process automation code is still needed. As much as possible, I'm trying to make that happen without writing code through TA.Gui, while still supporting advanced coding if user is a developer.

Do you know if Selenium Builder, or even Selenium IDE, is easily customizable to modify its generated output? I'm starting to work on the Chrome extension again (base on Resurrectio) to implement new function like capturing screenshots of webpage elements, hovering to an element and so on. Maybe if you are already working on Selenium-Builder solution it can be explored concurrently while I put on new functions through Resurrectio.

**Comment by kensoh** [comment]
Hi @jefleponot, thanks for adding on :) yes I'm aware of Ghost Inspector (backend using CasperJS/PhantomJS). A start-up friend is also using it to test their website. It is very easy to use and also records videos of the test automation. What Justin had done in the few short years to Ghost Inspector is admirable.

A problem for cloud deployment is the software will need to pass on AWS / DigitalOcean etc cloud hosting costs to the users. My guess is that's the reason why it is really hard to deploy cloud-based automation services for free, because the service provider will end up having to absorb all the AWS / cloud-servers costs.

I've considered providing a cloud service base on TA.Gui/CasperJS/PhantomJS in order to make automation accessible to more people. However, I'm not moving in that direction until there is real demand for it. I feel the more cost efficient way is for users to simply run locally using the horse-power they already have on their laptops/servers. Just need to find a way to remove user-friction in set-up. In that way, the automation tool can be kept free. It might end up some users are willing to pay for running on cloud while most users simply run on their computers/servers.

Another problem with Ghost Inspector or Selenium based solutions, with reference to RPA, is user cannot have fine-tuned logic and programmatic control without actually writing code. They are great for test automation but for process automation code is still needed. As much as possible, I'm trying to make that happen without writing code through TA.Gui, while still supporting advanced coding if user is a developer.

Do you know if Selenium Builder, or even Selenium IDE, is easily customizable to modify its generated output? I'm starting to work on the Chrome extension again (base on Resurrectio) to implement new function like capturing screenshots of webpage elements, hovering to an element and so on. Maybe if you are already working on Selenium-Builder solution it can be explored concurrently while I put on new functions through Resurrectio. Oh yeah, I haven't transitioned to automated testing as there are still many changes going on and working on that will probably slow down the pipeline. In the /src/test folder there are 2 files that might be the start of automated testing for the project, by comparing expected CasperJS script versus the actual generated one.

**Comment by jefleponot** [comment]
![image](https://cloud.githubusercontent.com/assets/5547697/23665286/509563f4-0358-11e7-9ead-6cf3cf4de60a.png)

For me selenium builder was a good free and easy to use tools but : 
- Xul is too difficult for community simple developer (now up-to-dated)
- running standalone doesn't work anymore since firefox 40
- lot of bugs with frames

Please have a look : https://addons.mozilla.org/fr/firefox/addon/selenium-builder/
David stark has continued this project but it was really difficult

**Comment by kensoh** [comment]
Thanks @jefleponot for adding on and sharing the screenshot, I have downloaded and tried it. As there isn't clear advantage to using Selenium Builder versus Resurrectio I'll continue building on the Resurrectio base.

Besides the cons you listed, it is too entrenched into the Selenium ecosystem. It will be a good base if the goal is export to Selenium WebDriver.

For the Resurrectio base it uses Zope recorder, there is also an issue #10 raised regarding frames which I'm keeping open for further investigation.

**Comment by kensoh** [comment]
Thanks @jefleponot for sharing your thoughts and the screenshot, I have downloaded and tried it. As there isn't clear advantage to using Selenium Builder versus Resurrectio I'll continue building on the Resurrectio base.

Besides the cons you listed, it is too entrenched into the Selenium ecosystem. It will be a good base if the goal is export to Selenium WebDriver.

For the Resurrectio base it uses Zope recorder, there is also an issue #10 raised regarding frames which I'm keeping open for further investigation.

**Comment by kensoh** [comment]
Fyi @jefleponot I've just made a commit to the Chrome extension with following comment -

"at beta, chrome extension can record navigating, clicking and entering text. have now added a right-click menu to use fetch, print, save, snap, move, wait steps conveniently.

have a feeling that chrome extension selectors can be further improved to integrate more tightly with ta.gui xpath/css selector, to chew more on this as more datapoints become available."

**Comment by jefleponot** [comment]
Hi @ken,

A menu is a brilliant idea but you mustn't do it in the same page as navigation because : 
- styles are applied on it
- if page use rightClick that will do conflict
- it is not user friendly

It will be nice to have another page or popup
with drawings instead of action label (in english )

**Comment by kensoh** [comment]
Thanks @jefleponot for your inputs! I see.. I've looked through your inputs and think that existing implementation is good for now.

- the menu style has already been coded to overwrite default page styling
- right-click is not often used on websites now as a primary interaction method
-  it is the most efficient way to rapidly record a flow due to being context-sensitive

By right-clicking on a webpage element and selecting the menu option, it directly converts into a TA.Gui step. Using an additional pop-up or toolbox will require tabbing/clicking somewhere else then clicking the webpage element to perform that function.

**Comment by kensoh** [comment]
Thanks @jefleponot for your inputs! I see.. I've looked through your inputs and think that existing implementation is good for now due to the following considerations.

- the menu style has already been coded to overwrite default page styling
- right-click is not often used on websites now as a primary interaction method
- it is the most efficient way to rapidly record a flow due to being context-sensitive

By right-clicking on a webpage element and selecting the menu option, it directly converts into a TA.Gui step. Using an additional pop-up or toolbox will require tabbing/clicking somewhere else then clicking the webpage element to perform that function.

**Comment by jefleponot** [comment]
How could you clean bad action ?

**Comment by kensoh** [comment]
In a usual recording, I'll record the whole sequence of events. After that edit or delete directly from the generated text file. The chrome extension for this project is primarily aimed to reduce user friction from identifying XPath or CSS, which may be challenging for some people. Because other than that, the normal automation flow file is just a few sentences of English. People just need to describe the interaction intention they want and it'll be converted into CasperJS JS code.

For ultimate expressiveness, will still need to rely on the list set of steps made as part of the tool. For example you may want to specify what filename to save the screenshot as, what variables to save the element text info to and so on.

In theory, all this can be implemented into the chrome browser. But am not sure in the longterm whether it will become too clunky. In the near-term, I'll probably focus on the other items with larger user impact such as enabling selection of option boxes, porting over to Windows etc.

GUI is great for ease of use, but for ultimate efficiency I typically prioritize text-based input versus GUI. For eg, I find developing directly using VI much more efficient than using Sublime or perhaps other IDE.

**Comment by kensoh** [comment]
In a usual recording, I'll record the whole sequence of events. After that edit or delete directly from the generated text file. The chrome extension for this project is primarily aimed to reduce user friction from identifying XPath or CSS, which may be challenging for some people. Because other than that, the normal automation flow file is just a few sentences of English. People just need to describe the interaction intention they want and it'll be converted into CasperJS JS code.

For ultimate expressiveness, will still need to rely on the list set of steps made as part of the tool. For example you may want to specify what filename to save the screenshot as, what variables to save the element text info to and so on.

In theory, all this can be implemented into the chrome extension. But am not sure in the longterm whether it will become too clunky. In the near-term, I'll probably focus on the other items with larger user impact such as enabling selection of option boxes, porting over to Windows etc.

GUI is great for ease of use, but for ultimate efficiency I typically prioritize text-based input versus GUI. For eg, I find developing directly using VI much more efficient than using Sublime or perhaps other IDE.

**Comment by kensoh** [comment]
In a usual recording, I'll record the whole sequence of events. After that edit or delete directly from the generated text file. The chrome extension for this project is primarily aimed to reduce user friction from identifying XPath or CSS, which may be challenging for some people. Because other than that, the normal automation flow file is just a few sentences of English. People just need to describe the interaction intention they want and it'll be converted into CasperJS JS code.

For ultimate expressiveness, will still need to rely on the list set of steps made as part of the tool. For example you may want to specify what filename to save the screenshot as, what variables to save the element text info to, what conditions and what you want to do with the variables, and so on.

In theory, all this can be implemented into the chrome extension. But am not sure in the longterm whether it will become too clunky. In the near-term, I'll probably focus on the other items with larger user impact such as enabling selection of option boxes, porting over to Windows etc.

GUI is great for ease of use, but for ultimate efficiency I typically prioritize text-based input versus GUI. For eg, I find developing directly using VI much more efficient than using Sublime or perhaps other IDE.

**Comment by kensoh** [comment]
spent some time looking at cancelling last action, not straightforward to undo more than 1 action. decided to cut loss for now and move on to porting to windows. committed base code below for revisiting in future - https://github.com/tebelorg/TA.Gui/commit/424539ebe16632436fcf56d4a646ca4d943a666f

**Comment by kensoh** [comment]
spent some time looking at cancelling last action, not straightforward to undo more than 1 action. since users can edit bad actions after recording, have decided to cut loss for now and move on to porting to windows. committed base code for revisiting in future - https://github.com/tebelorg/TA.Gui/commit/424539ebe16632436fcf56d4a646ca4d943a666f
