### ISSUE TITLE
PhantomJS Announcement, and TA.Gui v2.0 ideas

### ISSUE THREAD

**Issue by LeMoussel** [tebelorg/TA.Gui#21]
Headless Chrome is coming - https://www.chromestatus.com/features/5678767817097216
(https://news.ycombinator.com/item?id=14101233)

I think people will switch to it, eventually. Chrome is faster and more stable than PhantomJS. And it doesn't eat memory like crazy.

I don't see any future in developing PhantomJS. Developing PhantomJS 2 and 2.5 as a single developer is a bloody hell.
Even with recently released 2.5 Beta version with new and shiny QtWebKit, I can't physically support all 3 platforms at once (I even bought the Mac for that!). We have no support.
**From now, I am stepping down as maintainer. If someone wants to continue - feel free to reach me.**

Source :  https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE

**Comment by kensoh** [comment]
Hi @LeMoussel thanks for sharing the fresh news. Its sad news that Vitaly is stepping down from maintaining PhantomJS, but understandably so. Not sure if Ariya (PhantomJS creator) has other plans.

For TA.Gui, in the event there is no longer active development of PhantomJS, eventually over a long period of time standard web interfaces might deviate from it to the point that it becomes harder to automate interactions that might work on other headless variants. It also depends on whether CasperJS (now maintained by Jef) will consider adding support for another active headless browser. Hope the baton is passed on smoothly following Vitaly's call.

There's probably no change to current pipeline for TA.Gui, as CasperJS integration with SlimerJS/Firefox can be run headlessly using Xvfb. I'm also considering adding WebdriverIO as another target because it can basically run on any browser through Selenium and it has active developers community.

But it's too early to work on WebdriverIO for now. Am now exploring a few ideas for TA.Gui v2.0 - running automation flow by specifying a URL to the file, live debugging, integration with SikuliX for visual web automation in addition to using XPath/CSS-based selectors, integration with some form of online JSON datastore for example Kinto, removing friction for integrations such as H2O (for deep learning) and Arduino (real world interactivity) etc. Some will make it to v2.0 some won't, will only know as roadblocks appear along the way. But at the minimum, I think adding visual web automation will have the largest impact / benefits and I will experiment with some potential workflows through SikuliX's interactive mode.

Leaving this thread open for the time being for anyone's inputs on the PhantomJS's news, or TA Gui v2.0 ideas ;)

**Comment by kensoh** [comment]
Closing issue for now as there are no new inputs and v2.0 pipeline is more or less firmed up.

**Comment by kensoh** [comment]
Adding a note that CasperJS Team (Jef) would try to continue maintain CasperJS with future headless browsers such as Google Chrome. Yay! 😃 Details and status at this thread https://github.com/casperjs/casperjs/issues/1825

Also added below section to TagUI pipeline - 

What about TagUI v3.0? There are many changes lately in the web automation space. Chrome is coming up with an headless version, same for Firefox. PhantomJS's maintainer is stepping down. Depending on how these events pan out and CasperJS's response, TagUI may have to add new endpoints to its web automation framework in v3.0. Possible new endpoints include WebdriverIO (Selenium to various browsers) and Chrome Debugging Protocol (headless Chrome).

**Comment by kensoh** [comment]
Going to try integrate headless Chrome directly with TagUI, raised an issue to track - https://github.com/tebelorg/TagUI/issues/24

**Comment by babintheuns** [comment]
Hi Ken
Executing the sample file 1_google.tag used to work fine but after some updates on Fedora:
tagui /home/theuns/TagUI_Linux/tagui/flows/samples/1_google.tag
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Available platform plugins are: phantom.

Reinstalling the application may fix this problem.
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.

PhantonJS crashes on Fedora:
  Operating System: Fedora 33 (Workstation Edition)
       CPE OS Name: cpe:/o:fedoraproject:fedora:33
            Kernel: Linux 5.10.22-200.fc33.x86_64
      Architecture: x86-64

Any workarounds?
