### ISSUE TITLE
Windows defender reports an issue when downloading master as a zip package

### ISSUE THREAD

**Issue by lucaregini** [tebelorg/TA.Gui#8]
The reported virus is: Trojan:Win32/Sprinsky

**Comment by kensoh** [comment]
Hi @lucaregini thanks for your feedback! I've owned this issue and will try to replicate it on Windows. This is strange because the download is directly from GitHub shortener and download URL.

Note - TA.Gui is currently in beta (v0.6.0) and not yet tested on Windows. One thing for sure I know will break is its main runner which is written for shell script :)

**Comment by kensoh** [comment]
I had temporarily removed the file triggering false-positive and had contacted Eric Brehault to ask for his advice.

**Comment by kensoh** [comment]
https://github.com/tebelorg/TA.Gui/commit/348f78182c03427d5dbc95dbf65de211ffdafdcf - replaced temporary license with Eric's updated one. URL below shows that scan yields no false positive.

https://www.virustotal.com/en/file/84e6ceff55230d702968b5fc47113ad86587b9abb6b49a73acba6a5fee5f5de2/analysis/
