### ISSUE TITLE
I dont understand what's happening in the README gif

### ISSUE THREAD

**Issue by mayuroks** [tebelorg/TA.Gui#9]
I am a developer and I dont understand what's happening in the README gif. 

Can you please upload another one clearly shows the use case ? Or rather upload one more gif that simply shows the use case of web app automation.

**Comment by kensoh** [comment]
Thanks @mayuroks for your feedback. I see, the gif show the process of recording a series of steps using the Chrome extension, then made a simple edit to wait for few seconds, and finally playing the automation flow. Specifically, the steps are to sign up for accounts automatically in bulk. However, I stop at the submit step in order not to spam the website with garbage accounts.

I have problem going for longer duration for clear video, because the only way to embed video directly on the GitHub repo page is using a GIF. But file size will be huge, for example this one running for a minute takes 25MB. If it is too long, may be costly for some users for their mobile data. If embed using image with link to YouTube, users need to click in order to view the video, that will be very disruptive in reading the README.md.

I will check the video description at the bottom and make it clearer. There is also another example with details under HOW IT WORKS section. Appreciate your feedback and feel free to share your inputs on this issue page or to support@tebel.org
